# This is a basic workflow to help you get started with Actions

name: Complete workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Installing dependencies
        run: |
          echo "The processes are installing in sequential order"
          sudo apt update -y
          sudo apt install git -y
          sudo apt install python3-pip -y
          pip install pywinrm
          
      - name: Installing Ansible
        run: |
          sudo apt-get update && sudo apt-get install software-properties-common -y && sudo apt-add-repository --yes --update ppa:ansible/ansible
          sudo apt-get update -y
          sudo apt-get install ansible -y

      - name: Setting the config file
        run: |
          cp -r ansible.cfg /etc/ansible/
          
      - name: Running Playbook
        run: |
          ansible-playbook docker-create.yaml

      # Runs a set of commands using the runners shell
     # - name: Run a multi-line script
      #  run: |
       #   echo Add other actions to build,
        #  echo test, and deploy your project.
